// <auto-generated />
using BlazorProduct.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorProduct.Api.Migrations
{
    [DbContext(typeof(DBProducts))]
    [Migration("20220810042818_N")]
    partial class N
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Code Maze",
                            Name = "Travel Mug",
                            Price = 11.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Code Maze",
                            Name = "Classic Mug",
                            Price = 22.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Code Maze",
                            Name = "Code Maze Logo T-Shirt",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Code Maze",
                            Name = "Pullover Hoodie",
                            Price = 30.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
